version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "8080:80"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      FRONTEND_URL: ${FRONTEND_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_SECURE: ${SMTP_SECURE}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
      GCS_KEY_FILE_PATH: ${GCS_KEY_FILE_PATH}
      BOG_API_URL: ${BOG_API_URL}
      BOG_CLIENT_ID: ${BOG_CLIENT_ID}
      BOG_CLIENT_SECRET: ${BOG_CLIENT_SECRET}
      COPART_USERNAME: ${COPART_USERNAME}
      COPART_PASSWORD: ${COPART_PASSWORD}
      IAAI_USERNAME: ${IAAI_USERNAME}
      IAAI_PASSWORD: ${IAAI_PASSWORD}
    volumes:
      - ./uploads:/app/uploads
      - ./keys:/app/keys
    networks:
      - backend-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - backend-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    #entrypoint: /bin/sh -c
    # This will only run once to get the cert, see instructions below
    # "certbot certonly --webroot --webroot-path=/var/www/certbot --email levanzhvania96@gmail.com --agree-tos --no-eff-email -d crx-platform.vercel.app"

networks:
  backend-network:
    driver: bridge
