version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - app
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email levanzhvania96@gmail.com --agree-tos --no-eff-email -d crx-platform.vercel.app -d www.crx-platform.vercel.app

volumes:
  certbot-etc:
  certbot-var:

networks:
  app-network:
    driver: bridge
